## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file main.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_181 = Integer(181); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_195 = Integer(195); _sage_const_2 = Integer(2); _sage_const_227 = Integer(227); _sage_const_0p01 = RealNumber('0.01')## This file (main.sagetex.sage) was *autogenerated* from main.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('main', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_181 
_st_.blockbegin()
try:
 x=var('x');
 t = var('t');
 x_coords = [t for t in srange(_sage_const_0 ,_sage_const_2 ,_sage_const_0p01 )];
 
 x = var('x');
 p = var('p');
 w0 = _sage_const_2 *pi; Q = _sage_const_2 ; __tmp__=var("x"); v = symbolic_expression(inverse_laplace(_sage_const_1 /p/(_sage_const_1 +p/Q/w0+p**_sage_const_2 /w0**_sage_const_2 ), p, x)).function(x);
 
 y5_coords = [v(x).n() for x in x_coords];
 
 output = "";
 for i in range(_sage_const_0 ,len(x_coords)-_sage_const_1 ):
     output += "\draw[orange, thick] ("+str(x_coords[i])+","+str(y5_coords[i])+")--("+str(x_coords[i+_sage_const_1 ])+","+str(y5_coords[i+_sage_const_1 ])+");\n";
except:
 _st_.goboom(_sage_const_195 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_227 
 _st_.inline(_sage_const_0 , output)
except:
 _st_.goboom(_sage_const_227 )
_st_.endofdoc()

